steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/infytel-419119/demo-repo/spring-docker-demo:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/infytel-419119/demo-repo/spring-docker-demo:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/spring-deployment'
      - 'spring-container=us-central1-docker.pkg.dev/infytel-419119/demo-repo/spring-docker-demo:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'

images:
  - 'us-central1-docker.pkg.dev/infytel-419119/demo-repo/spring-docker-demo:$SHORT_SHA'
