apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-container
          image: us-central1-docker.pkg.dev/infytel-419119/demo-repo/spring-docker-demo:latest
          ports:
            - containerPort: 8080
